{{/*
Copyright (C) 2025 XM Cyber
Author: Devops Infra Team
*/}}

{{- define "global-templates.pdb" -}}
{{- $global_values := .Values.global}}
{{- $default_values := .Values.pdb_defaults }}
{{- $common_defaults := .Values.common_defaults }}
{{- range .pdbs }}
{{- if not .disabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .name | default (include "common.names.fullname" $) }}
  namespace: {{ include "helpers.prefixNamespace" (dict "namespace" .namespace "global" $global_values) }}
  labels: {{ include "helpers.labels" (dict "context" $ "customLabels" .labels "defaultLabels" $common_defaults.labels) | nindent 4 }}
  {{- if or .annotations $common_defaults.annotations .reloaderEnabled }}
  annotations: {{ include "helpers.annotations" (dict "context" $ "customAnnotations" .annotations "defaultAnnotations" $common_defaults.annotations "reloaderEnabled" .reloaderEnabled) | nindent 4 }}
  {{- end }}
spec:
  minAvailable: {{ .minAvailable | default $default_values.minAvailable }}
  selector:
    matchLabels: {{ .matchLabels | default $default_values.matchLabels | toYaml | nindent 6 }}
{{- end }}
{{- end }}
{{- end }}
