{{/*
Copyright (C) 2024 XM Cyber
Author: Devops Infra Team
*/}}

{{- define "global-templates.sealedsecret" -}}
{{- $global_values := .Values.global}}
{{- $default_values := .Values.sealedsecrets_defaults }}
{{- $common_defaults := .Values.common_defaults }}
{{- range .sealedsecrets }}
{{- if not .disabled }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .name | required "name is required for each sealedsecret" }}
  namespace: {{ include "helpers.prefixNamespace" (dict "namespace" .namespace "global" $global_values) }}
  {{- if or .annotations $common_defaults.annotations }}
  annotations: {{ include "helpers.annotations" (dict "context" $ "customAnnotations" .annotations "defaultAnnotations" $common_defaults.annotations) | nindent 4 }}
  {{- end }}
spec:
  {{- if .encryptedData }}
  encryptedData:
  {{- range $key, $val := .encryptedData }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end}}